### ISSUE TITLE
Windows 的 emoji 不显示，需要指定对应的字体名称

### ISSUE THREAD

**Issue by mingcheng** [wongdean/rime-settings#10]
如题，同时需要注意 Win10 的版本（如果是 Win7 需要手动安装对应的 emoji 字体）

这里可以做个参考：https://emojipedia.org/microsoft/

手头上目前没有 Windows 的机子，所以无法测试这里暂时只能先给个思路。

**Comment by wongdean** [comment]
https://github.com/rime/rime-emoji/issues/5

我看的是，框架不支持显示成彩色
