### ISSUE TITLE
如何实现数字键候选词多选项

### ISSUE THREAD

**Issue by masonincn** [wongdean/rime-settings#11]
如何实现 `/` + `数字` 显示下图效果？

![Ro8Um4yhknWQFxC](https://i.loli.net/2020/04/05/Ro8Um4yhknWQFxC.png)

**Comment by masonincn** [comment]
另：如何实现 `/` + `数字` 显示下图效果？

![Ro8Um4yhknWQFxC](https://i.loli.net/2020/04/05/Ro8Um4yhknWQFxC.png)

**Comment by wongdean** [comment]
这个好像是自定义symbols吧，你参照别的项目改改，短期（20天内）不准备弄，后面有时间会加

**Comment by wongdean** [comment]
@masonincn 全拼状态下可以实现数字输入，但是双拼我实在没办法解决。。
