### ISSUE TITLE
请问支持自然码双拼吗？ 

### ISSUE THREAD

**Issue by baopengsun** [wongdean/rime-settings#12]
是否可以直接使用自然码双拼？ 支持辅助码吗？ 谢谢！

**Comment by wongdean** [comment]
支持了，刚提交了，经测试，“应该”没有问题（直接用的小鹤的配置）

**Comment by azazjjyjjy** [comment]
> 支持了，刚提交了，经测试，“应该”没有问题（直接用的小鹤的配置）

default.custom.yaml 直接在这里面启用double_pinyin好像不行，打不了汉字，切换小鹤没问题。是方法不对吗

**Comment by wongdean** [comment]
@azazjjyjjy 我刚试了没有问题啊。。。你是全部用我的配置吗？

**Comment by azazjjyjjy** [comment]
> @azazjjyjjy 我刚试了没有问题啊。。。你是全部用我的配置吗？

是的。我现在重新下载了个mspy 微软双拼方案丢进去可以用

**Comment by wongdean** [comment]
@azazjjyjjy 我自己测试的没有问题。。。如果后面谁遇到了再提 issue 吧。。
