### ISSUE TITLE
github下载很缓慢，能否copy一份到gitee上，方便国内下载

### ISSUE THREAD

**Issue by Hoking007** [wongdean/rime-settings#16]
github下载很缓慢，能否copy一份到gitee上，方便国内下载

**Comment by wongdean** [comment]
@Hoking007 主要我没有码云，我弄个网盘吧

**Comment by Hoking007** [comment]
> @Hoking007 主要我没有码云，我弄个网盘吧

作者的东西非常好，我正在clone，不过断开了好几次，可能是字体比较大吧

**Comment by Hoking007** [comment]
![image](https://user-images.githubusercontent.com/55968385/80374773-ca2d6c80-88c9-11ea-9bd5-d666af1e2614.png)

**Comment by wongdean** [comment]
挂代理会快很多。。。以前想过放到网盘，但是没办法做到实时更新。

**Comment by Hoking007** [comment]
我用香港专线下载了，比较快！谢谢楼主分享！

**Comment by wongdean** [comment]
@Hoking007 那我还是弄一个通道吧，应群众的要求。使用过程有什么问题记得看说明，没写清楚的就提issue

**Comment by Hoking007** [comment]
> @Hoking007 那我还是弄一个通道吧，应群众的要求。使用过程有什么问题记得看说明，没写清楚的就提issue

gitee可以直接导入github仓库，感谢楼主！词库很好！建了自己分支加上自己的词库搭配起来很舒服，会定期merge楼主更新

**Comment by wongdean** [comment]
@Hoking007 可，词库上我试了自己转的，但是不知道怎么总是出问题，后来又替换为git上另外一个项目的。另外码云我没有，如果方便的话劳烦您建一下？

**Comment by Hoking007** [comment]
import_tables:
  - luna_pinyin
  - luna_pinyin.sgmain
  - luna_pinyin.sgplus
  - luna_pinyin.sgplus2
  - luna_pinyin.chat
  - luna_pinyin.computer
  - luna_pinyin.place
  - luna_pinyin.shopping
  - luna_pinyin.net
  - luna_pinyin.website
  - luna_pinyin.poetry
  #
  - luna_pinyin.hoking #指向 luna_pinyin.hoking.dict.yaml 文件

然后把luna_pinyin.hoking.dict.yaml文件拷贝到rime目录重新部署

这个词库是我之前搜狗词库转换过来的

**Comment by wongdean** [comment]
@Hoking007 加个微信吧，dzUxMjEyOTQ3Nw==（base64）

**Comment by Hoking007** [comment]
我clone了一份到gitee上，方便国内下载
https://gitee.com/Hoking/rime-settings

**Comment by Hoking007** [comment]
> @Hoking007 加个微信吧，dzUxMjEyOTQ3Nw==（base64）

好的，可以搜索hoking007微信号
