### ISSUE TITLE
[Advice]建议集成easy-en方案

### ISSUE THREAD

**Issue by ayalhw** [wongdean/rime-settings#17]
建议集成easy-en方案

https://github.com/BlindingDark/rime-easy-en

这个方案对于英文及汉语中夹杂的英文输入有很大帮助

**Comment by wongdean** [comment]
@ayalhw ok，我研究一下，感谢

**Comment by wongdean** [comment]
@ayalhw 已经完成。

**Comment by ayalhw** [comment]
感谢

**Comment by seagle0128** [comment]
升级后好像逗号句号选择无法使用了，能看看吗？

**Comment by wongdean** [comment]
> 升级后好像逗号句号选择无法使用了，能看看吗？

具体说说？没太明白你的意思

**Comment by seagle0128** [comment]
这两条不起作用了

```elisp
- {accept: comma, send: Page_Up, when: paging}
- {accept: period, send: Page_Down, when: has_menu}
```

**Comment by wongdean** [comment]
> 这两条不起作用了
> 
> ```emacs-lisp
> - {accept: comma, send: Page_Up, when: paging}
> - {accept: period, send: Page_Down, when: has_menu}
> ```

已修复
