### ISSUE TITLE
打不出 濛  这个字

### ISSUE THREAD

**Issue by chenzhenjia** [wongdean/rime-settings#19]
![image](https://user-images.githubusercontent.com/11611967/83837845-276ad800-a72a-11ea-9bd7-26c302464db1.png)
![image](https://user-images.githubusercontent.com/11611967/83837866-30f44000-a72a-11ea-8dfc-99a03a118ad7.png)
我在自定义配置里面配置了  濛 但是输入法还是打不出来

**Comment by wongdean** [comment]
濛 被转换成简体 蒙，所以没有出现在候选中

**Comment by chenzhenjia** [comment]
> 蒙被转换成简体蒙，所以没有出现在预设中

可以不转换吗？是配置的问题，还是rime的问题呢

**Comment by wongdean** [comment]
确定不是配置的问题，是不是Rime的问题我也不清楚。建议到Rime主仓库提交issue，看佛振是否有答复。这个问题，恕我无能为力。解决了之后还请告知。。。

**Comment by chenzhenjia** [comment]
> 确定不是配置的问题，是不是Rime的问题我也不清楚。建议到Rime主仓库提交issue，看佛振是否有答复。这个问题，恕我无能为力。解决了之后还请告知。。。

我去了rime的仓库看了一下，好多 issues，最后一次提交都是1年前了，是不是已经不维护了

**Comment by wongdean** [comment]
> 我去了rime的仓库看了一下，好多 issues，最后一次提交都是1年前了，是不是已经不维护了
并不是，代码一直在提交，有些 issue 暂时无法解决就一直留着的

**Comment by wongdean** [comment]
> 我去了rime的仓库看了一下，好多 issues，最后一次提交都是1年前了，是不是已经不维护了

并不是，代码一直在提交，有些 issue 暂时无法解决就一直留着的

**Comment by chenzhenjia** [comment]
你好！我在rime仓库提了个issue，开发者说是使用了的问题 [issue](https://github.com/rime/home/issues/568)，请问怎么在配置里面解决呢

**Comment by wongdean** [comment]
> 你好！我在rime仓库提了个issue，开发者说是使用了的问题 [issue](https://github.com/rime/home/issues/568)，请问怎么在配置里面解决呢

开发者的意思是，简体输入法是无法打出这个字的。如果您想打出这个字，需要切到繁体输出才可以。

本输入法中，切换到繁体，在输入界面，按：

Ctrl + ` (Tab上面那个)选第二项“中/Y/半/汉"（可能是“中/N/半/汉"），里面有简繁切换的

**Comment by chenzhenjia** [comment]
是的，用快捷键切换后可以打出来了。
