### ISSUE TITLE
中文的「-」无法使用

### ISSUE THREAD

**Issue by mengjx0777** [wongdean/rime-settings#2]
系统：10.15.4
Rime：0.14.0
朙月拼音_简化字，中文输入下 键盘的「-」没有响应 ，但是⇧+「-」（──）是正常的，
英文输入下正常，比如我在提交这个issues的时候，「-」就是英文下输出的

**Comment by wongdean** [comment]
确实存在这个问题，最开始配置的时候，「-」不能翻页，后来可以翻页了，「-」无法在中文状态下打出来。请有能力的大佬解决一下

**Comment by ivanberry** [comment]
搭车问一下，如何获取应用的全名呀？用于配置默认的输入法是否为英文。

**Comment by mengjx0777** [comment]
修改default.custom.yaml 中的
   ` - { when: always, accept: minus, send: Page_Up }`
   改为：
   ` - { when: has_menu, accept: minus, send: Page_Up }`
 或者修改
   `key_binder/bindings:`
   改为：
   `paging_with_minus_equal: # 设置哪些键可以翻页
       __append:`

已解决~

**Comment by wongdean** [comment]
@mengjx0777 多谢，已修复
