### ISSUE TITLE
覆盖重新部署后托盘图标两个“中”

### ISSUE THREAD

**Issue by poorich** [wongdean/rime-settings#21]
RT
win10(2004) 小狼毫 0.14.3.0
重部署时出现水杯，部署完毕后水杯变成另一个“中”，重启之类的操作无法让它消失
整个人愣住……
![](https://imgs.aixifan.com/o_1ed9goga118gj1anp1uhm10au14dh7.png)

**Comment by wongdean** [comment]
> RT
> win10(2004) 小狼毫 0.14.3.0
> 重部署时出现水杯，部署完毕后水杯变成另一个“中”，重启之类的操作无法让它消失
> 整个人愣住……
> ![](https://camo.githubusercontent.com/601add2a38b171052d246b445edb564a16053092/68747470733a2f2f696d67732e6169786966616e2e636f6d2f6f5f31656439676f6761313138676a31616e703175686d3130617531346468372e706e67)

这个问题，请移步至 https://github.com/rime/weasel/issues 反映。这个实在没有能力解决，主要也是我现在无法复现。能够提供的建议包括：
1）卸载重装，2）重启

（感觉我说了跟没说一样的，哈哈哈）

**Comment by poorich** [comment]
搞定了，是 weasel.custom.yaml 里的
"style/display_tray_icon": true
把它关了就好了
