### ISSUE TITLE
输出简体字时八股文配置有误导致词频排序无效

### ISSUE THREAD

**Issue by Lamb-Yang** [wongdean/rime-settings#25]
原方案里的八股文配置是
```
patch:
  __include: grammar:/hant
```
自己在使用的时候发现词频没有自动调整，看了下八股文的说明，如果打简体字需要改为
```
patch:
  __include: grammar:/hans
```
自己改了之后词频能正常调整了。

**Comment by wongdean** [comment]
由于词库是繁体，配置八股文也是繁体，程序最后统一转为简体。这个不算错误，我没有测试这个改动对输入有何影响。
词频（包括自造词）我用仓库中的配置没有任何问题呀，您考虑是否是打完字又删了，这样不会计入词频的。
另外如果遇到同类问题的小伙伴可考虑此改动，仓库中我就不改了，如果有多人反馈再改。

**Comment by Lamb-Yang** [comment]
谢谢，貌似如你所说可能是我打完又删的缘故。忘记词库本身就是繁体的了，所以原配置应该是没有问题的。
