### ISSUE TITLE
皮肤修改不生效

### ISSUE THREAD

**Issue by wallover** [wongdean/rime-settings#3]
![image](https://user-images.githubusercontent.com/24579471/78105859-b99de980-7424-11ea-850b-67cdb8a375ea.png)
如图，修改color_scheme的值后重新部署了，发现皮肤没有生效，mac os 10.15.4

**Comment by wallover** [comment]
重新部署后不需要重启或者注销操作就能生效吧？

**Comment by wongdean** [comment]
@wallover 直接修改就可以呀，我感到很困惑因为我的立刻就生效了……
![BUmPtD](https://wang-1258168870.cos.ap-guangzhou.myqcloud.com/BUmPtD.png)

**Comment by yangjingchuang** [comment]
> @wallover 直接修改就可以呀，我感到很困惑因为我的立刻就生效了……
> ![BUmPtD](https://camo.githubusercontent.com/09c2890f38a72bf5633691a59be33fcf11b89a8c/68747470733a2f2f77616e672d313235383136383837302e636f732e61702d6775616e677a686f752e6d7971636c6f75642e636f6d2f42556d5074442e706e67)

楼主，我也有这个问题，我是win10下面使用的，另外

**Comment by yangjingchuang** [comment]
![image](https://user-images.githubusercontent.com/29910922/78207002-f6c0b500-74d2-11ea-9906-c40201164258.png)

**Comment by jostyee** [comment]
修改后重新deploy一次

**Comment by yangjingchuang** [comment]
> 修改后重新deploy一次

这个是必须的，也尝试过了的，没办法卸载重新使用也不可以，但是词库好像是可以使用的。

**Comment by yangjingchuang** [comment]
> > 修改后重新deploy一次
> 
> 这个是必须的，也尝试过了的，没办法卸载重新使用也不可以，但是词库好像是可以使用的。



> 修改后重新deploy一次

> 修改后重新deploy一次

是不是 win 下不兼容之类的呀

**Comment by wongdean** [comment]
@yangjingchuang 是不管啥皮肤都不管用吗？还只是换皮肤不生效？
另外这个兼容性问题没有测试过，没有别的设备，过段时间搞个虚拟机

**Comment by yangjingchuang** [comment]
> @yangjingchuang 是不管啥皮肤都不管用吗？还只是换皮肤不生效？
> 另外这个兼容性问题没有测试过，没有别的设备，过段时间搞个虚拟机

楼主我不敢臆断，等你有空了在 win 下试下看看效果

**Comment by yangjingchuang** [comment]
> @yangjingchuang 是不管啥皮肤都不管用吗？还只是换皮肤不生效？
> 另外这个兼容性问题没有测试过，没有别的设备，过段时间搞个虚拟机

在 win 下应该不可以完美适配吧，比如说这个圆角，在 win 下就是失效的

**Comment by wongdean** [comment]
@yangjingchuang 不能完全适配，我上传了一个小狼毫的配置，默认的是别的地方找的win10自带的皮肤。确实我试了 majava_dark 和 apathy 都不支持，就像是一个地方缺一块似的

**Comment by wongdean** [comment]
@yangjingchuang 刚刚新加了一个文件`weasel.custom.yaml`，你把它下载下来放到文件夹重新配置（好歹能看了

**Comment by yangjingchuang** [comment]
> @yangjingchuang 不能完全适配，我上传了一个小狼毫的配置，默认的是别的地方找的win10自带的皮肤。确实我试了 majava_dark 和 apathy 都不支持，就像是一个地方缺一块似的

好吧，那现在可以使用了还是？？？

**Comment by yangjingchuang** [comment]
> @yangjingchuang 刚刚新加了一个文件`weasel.custom.yaml`，你把它下载下来放到文件夹重新配置（好歹能看了

我再试试看下效果，辛苦了

**Comment by yangjingchuang** [comment]
> @yangjingchuang 是不管啥皮肤都不管用吗？还只是换皮肤不生效？
> 另外这个兼容性问题没有测试过，没有别的设备，过段时间搞个虚拟机

![image](https://user-images.githubusercontent.com/29910922/78215459-1fa07480-74ea-11ea-9a90-8ae38b7aaad5.png)
可能是我的操作有问题吧，有空再弄下
