### ISSUE TITLE
请持续更新词库

### ISSUE THREAD

**Issue by seagle0128** [wongdean/rime-settings#30]
很喜欢这个Rime 设置，用了很长一段时间了。唯一缺憾还是词库太小，很多词汇答不出来，影响了输入速度。

我看到另外一个配置，在持续从搜狗导出更新词库，是否也可以持续更新呢？请参考：

https://github.com/alswl/Rime

**Comment by wongdean** [comment]
多谢，今天会测试一下，需要先跟原作者联系

**Comment by wongdean** [comment]
下周更新吧，这个词库我用了一段时间，挺好的

**Comment by liziqiang** [comment]
一个小工具可以根据配置下载搜狗字库并合并转换，希望对你有帮助哈~
https://github.com/liziqiang/scel2txt

**Comment by wongdean** [comment]
多谢多谢，这些词库的最大弊端就是现在已经很老了，搜狗的词库绝大部分都是10年前后出的，现在的新词根本跟不上。如果长时间都用一个输入法，就可以自己养了，词库就特别顺手~

**Comment by seagle0128** [comment]
Thank you!
