### ISSUE TITLE
readme.md 里面加上皮肤预览吧？

### ISSUE THREAD

**Issue by yichangshengwu** [wongdean/rime-settings#32]
不然，
还要自己一个一个地尝试具体效果，
我懒！
（不要打我

**Comment by wongdean** [comment]
这个暂时没考虑，你在本地使用的话改一下参数重新部署就行了。也可以自己调整。
最主要是，同一个皮肤在不同的系统下是不一样的。抱歉哈。

**Comment by yichangshengwu** [comment]
> 这个暂时没考虑，你在本地使用的话改一下参数重新部署就行了。也可以自己调整。
> 最主要是，同一个皮肤在不同的系统下是不一样的。抱歉哈。

要说抱歉的该是我呀，自己懒直接来伸手了 （捂脸
