### ISSUE TITLE
编辑拓展词库

### ISSUE THREAD

**Issue by linchen123** [wongdean/rime-settings#33]
我想导入搜狗的医药词库按教程搞了一天都不成功，是我转换的有问题吗？这是倒出来的 请帮我看看对不对，谢谢！
Mac OS格式的

链接: https://pan.baidu.com/s/1JUhkiIGMelygCwfJ7aFH7g 提取码: fij9

**Comment by DO-ITNOW** [comment]
你把词库的名字改短一点试试
