### ISSUE TITLE
easy-en不生效

### ISSUE THREAD

**Issue by Jacobax** [wongdean/rime-settings#34]
复制部署后测试输入英文，easy不生效。在luna_pinyin.extended.dict.yaml中发现没有easy-en，加上后还是有问题
没有预测
![1](https://user-images.githubusercontent.com/23228895/100675566-24336a80-33a2-11eb-8439-5f086adf199e.png)
单词全拼有前面为大写后面为小写的情况
![2](https://user-images.githubusercontent.com/23228895/100675711-6d83ba00-33a2-11eb-8db0-80c969acb781.png)
总之，加上easy-en有拼写和候选词频的问题

**Comment by Jacobax** [comment]
![3](https://user-images.githubusercontent.com/23228895/100676317-a5d7c800-33a3-11eb-856d-001df0d82dc6.png)

**Comment by Jacobax** [comment]
还有，luna_pinyin.flypyfz.dict.yaml这个形码辅助词库加上后部署不了

**Comment by Jacobax** [comment]
细看了更新记录才发现在custom.yaml里是默认注释掉的，去掉注释后英文输入没问题了

**Comment by poorich** [comment]
@Jacobax  请问是去掉哪的注释？ ```luna_pinyin.custom.yaml``` 的最后四行吗？

**Comment by Jacobax** [comment]
> 
> 
> @Jacobax 请问是去掉哪的注释？ `luna_pinyin.custom.yaml` 的最后四行吗？
> `luna_pinyin.custom.yaml` 的最后四行原来是默认打开的，但好像因为下划线的输入会有些问题给他关了

这两行去掉注释，我小鹤双拼没发现什么大问题
  # __include: easy_en:/patch
  # easy_en/enable_sentence: false

**Comment by Thinkbond** [comment]
> > @Jacobax 请问是去掉哪的注释？ `luna_pinyin.custom.yaml` 的最后四行吗？
> > `luna_pinyin.custom.yaml` 的最后四行原来是默认打开的，但好像因为下划线的输入会有些问题给他关了
> 
> 这两行去掉注释，我小鹤双拼没发现什么大问题
> # __include: easy_en:/patch
> #easy_en/enable_sentence: false

去掉注释以后，表情符号不能输出了。。（小鹤双拼）
