### ISSUE TITLE
修改候选项背景颜色问题

### ISSUE THREAD

**Issue by masonincn** [wongdean/rime-settings#4]
```
hilited_candidate_back_color: 0xFFF0E4
hilited_candidate_text_color: 0xEE6E00
```
比如上方颜色代码尸0x开头，想修改为macOS自带的颜色 `215BD0`，如何转换？

**Comment by wongdean** [comment]
将0x后面那一串直接替换？我不是特别清楚……应该是这样，您自己试试

**Comment by masonincn** [comment]
还有一个疑问，文本替换后面的排序无效；
或者下图同一个输入码对应两个或多个文本，后面的数字必须倒序才有效，也就是 `2`对应的首选项。

![jq5Nm4CzEOMnrXa](https://i.loli.net/2020/04/01/jq5Nm4CzEOMnrXa.png)

**Comment by wongdean** [comment]
@masonincn 没听明白你的意思，自定义输入码加权重时要注意两点：1、「Tab」隔开，2、权重大的排在前面，上图中打「as」肯定是第一个排在第二个前面（2>1）

**Comment by masonincn** [comment]
第1点：比如 `cm`对应 `⌘`，`⌘` 默认在候选词条第一个，如何让它显示在第二个

第2点明白了，之前认为 `1` 排在第一个，我理解错误。

**Comment by wongdean** [comment]
@masonincn 如果词库里面带了权重，应该是可以和自定义词语比大小的（我猜的，我的词库没有权重）
事实是，自定义短语一直排在第一个

能做的：设置自定义短语的时候小心，如设置手机号，那可以设置为「sjh」，这样基本不会冲突，耽误到你选字。

**Comment by masonincn** [comment]
感谢解答，解决疑问。
