### ISSUE TITLE
GUN/Linux -> GNU/Linux

### ISSUE THREAD

**Issue by Mosney** [wongdean/rime-settings#42]
https://github.com/wongdean/rime-settings/blob/68528e4e00d0995ef4e61cf5c2b0cca004828e35/custom_phrase.txt#L64

另外不知道为什么，输入`linux`并不会出现这个词组，如截图所示
linux
![image](https://user-images.githubusercontent.com/22477230/106881087-0f63b200-6718-11eb-9ae8-5704359e1430.png)

**Comment by wongdean** [comment]
这个问题是因为你这一行：
`GUN/Linux linux `
中间的空，你敲的是空格，应该是制表符\t

如果自定义的话，建议中间的空格从前面复制，不要自己手敲。我测试是没有问题的

**Comment by Mosney** [comment]
我没修改过这个文件啊，直接打包下载后扔进去的

**Comment by Mosney** [comment]
![image](https://user-images.githubusercontent.com/22477230/109530960-47310000-7af2-11eb-9ec7-1699b7a485ac.png)

刚刚又去repo里单独下在这个文件确认了一下，的确是本来就是拼写错误+制表符被替换成了空格。
此错误是在https://github.com/wongdean/rime-settings/commit/cadfb03289d135ffb54ae29934019a8bbf29588c 被引入的

**Comment by wongdean** [comment]
> ![image](https://user-images.githubusercontent.com/22477230/109530960-47310000-7af2-11eb-9ec7-1699b7a485ac.png)
> 
> 刚刚又去repo里单独下在这个文件确认了一下，的确是本来就是拼写错误+制表符被替换成了空格。
> 此错误是在[cadfb03](https://github.com/wongdean/rime-settings/commit/cadfb03289d135ffb54ae29934019a8bbf29588c) 被引入的

不好意思，这是另一位伙伴提的，我周末会修的，感谢哈

**Comment by Mosney** [comment]
> 不好意思，这是另一位伙伴提的，我周末会修的，感谢哈

刚刚开了个PR，通过一下就可以了
