### ISSUE TITLE
请问一下如何开启快速输入日期、时间

### ISSUE THREAD

**Issue by Nthin** [wongdean/rime-settings#44]
按照网上其他人的教程在lua目录下放了lua脚本，在rime.lua中引入了，并没有生效。
请问一下如何开启快速输入日期、时间，谢谢🙏🏻

**Comment by superhxl** [comment]
按照教程把相关脚本引入rime.lua，然后在所在输入法配置文件中（我是luna_pinyin.custom.yaml）中enginer/translator部分的 - lua_translator@date_translator的注释去掉，重新部署即可。

**Comment by Nthin** [comment]
> 按照教程把相关脚本引入 rime.lua，然后在所在输入法配置文件中（我是 luna_pinyin.custom.yaml）中 enginer/translator 部分的 - lua_translator@date_translator 的注释去掉，重新部署即可。

已解决，感谢🙏🏻
