### ISSUE TITLE
混合输入候选条高度不固定，打字抖动

### ISSUE THREAD

**Issue by EeeMt** [wongdean/rime-settings#49]
如图，是否有配置可以支持设置固定高度啊
![Kapture 2021-02-25 at 20 10 30](https://user-images.githubusercontent.com/21380583/109152120-065d8200-77a6-11eb-96cc-4a4aa6ef5af9.gif)
![Kapture 2021-02-26 at 10 13 07](https://user-images.githubusercontent.com/21380583/109245424-67736d00-781b-11eb-8cab-becfcd11c09c.gif)

**Comment by wongdean** [comment]
这个锅我背不了，哈哈哈哈，这是Rime官方的锅，0.15以上的版本均有此问题，含有emoji的都会抖动

**Comment by EeeMt** [comment]
哈哈哈， 好吧
