### ISSUE TITLE
朙月拼音设置多反查无法生效

### ISSUE THREAD

**Issue by poorich** [wongdean/rime-settings#51]
反查功能是Rime一大亮点
设置多反查略显麻烦
成功的案例有
https://github.com/rime/rime-cantonese/blob/master/jyut6ping3.schema.yaml
https://github.com/rime/rime-jyutping/blob/master/jyutping.schema.yaml
我模仿其结构给两分方案设置了多反查，是生效了的
想给朙月拼音也设置一组，却无法生效，关闭easy_en也不生效
请问会是什么原因？

**Comment by wongdean** [comment]
你好，请问反查使用的情景是：
> 主输入法是五笔，但是忘了某个字的键码，然后用拼音打出然后反查出五笔的键码

的意思吗？

我自己很少用这个功能，如果有必要我下周末会研究测试一下，加上去的，不好意思哈

**Comment by poorich** [comment]
你又客气体贴得回复我了
反查使用的情景如你所说
我中意的主输入法是朙月拼音（拼音万岁）
用于反查的方案为[【两分】](https://github.com/szc126/rime-liangfen)与[【山人】](https://github.com/siuze/sunman)

加上去的话，可以考虑把两分加进去，才两个文件，该方案也比较实用
测试的话不妨用两分和笔划测试？

不生效的原因恐怕很隐蔽，我想不会是方案配置存在什么漏洞
说起来，配置里几组 `schema.yaml` 与 `custom.yaml` 之间重复较多，可以适当去重

**Comment by wongdean** [comment]
我只添加了一个二分的反差，是可以生效的，讲道理多组应该是一样的，你试试看。
默认是未启用的，你需要查看`luna_pinyin_custom_yaml`，打开反查注释，我有写说明。

**Comment by wongdean** [comment]
另外，`custom`和`schema`很多重复的，这个基本上每个相对默认都有修改，所有就随他去吧。你可以自行修改，如果后续加了什么东西，你直接看diff就可以了。
反查方案这个我就按照你的要求加了一个二分的，虽然笔画和二分的我都不太会用哈哈哈。

有什么问题继续提 issue

**Comment by poorich** [comment]
谢谢你增加的功能

**Comment by wongdean** [comment]
> 谢谢你增加的功能
> 在音码方案上，这个方案已经非常完善
> 给形码留下些反查接口的当下，就显得更好用了

哈哈哈哈，这是夸吗，很高兴能帮到你，有要求继续提！
