### ISSUE TITLE
最新版本的鼠须管中会自动删除luna_pinyin.schema.yaml

### ISSUE THREAD

**Issue by Eason0210** [wongdean/rime-settings#56]
@wongdean  在最新版本的鼠须管中部署成功后，会自动将`luna_pinyin.schema.yaml` 这个文件移动到Rime目录下的trash文件夹下。请问有人知道是什么问题吗？

在Windows 中的小狼毫没有这个问题

**Comment by wongdean** [comment]
我倒没主意，好像确实这个文件不在了，但是这个没有影响啊……这个文件是默认的朙月拼音配置文件，如果你要自定义，修改对应的`custome.yaml`文件就好，不自定义的话更不需要修改了

**Comment by Eason0210** [comment]
多谢，确认不需要的话，我就把这个文件从本地的配置仓库去掉了，免得每次部署都会删除。

**Comment by wongdean** [comment]
确认不需要。

**Comment by Eason0210** [comment]
感谢。刚才我在小狼毫也测试了一下，这个文件确实是rime在build的时候自动生成的，小狼毫版本0.14.3，会自动生成在Rime用户文件夹的根目录。而鼠须管最新版0.15.2 ，为了避免用户修改这个文件，自动将这个文件生成在build文件夹中，同时会自动将根目录下的`luna_pinyin.schema.yaml`文件移动到trash 文件夹内。
