### ISSUE TITLE
emoji 显示不全是我系统的问题么？

### ISSUE THREAD

**Issue by yrkj** [wongdean/rime-settings#57]
你好，如题。

系统: macOS 10.15.7 (19H2)
![image](https://user-images.githubusercontent.com/1813638/119375287-36f18100-bced-11eb-9a2d-d3489e226467.png)
![image](https://user-images.githubusercontent.com/1813638/119375316-3eb12580-bced-11eb-9989-0047f750eb0c.png)

**Comment by sudoyang** [comment]
我也碰到相同问题，题主怎么解决的啊？
