### ISSUE TITLE
你好  可以加上小鹤的形码吗 

### ISSUE THREAD

**Issue by ClenLu** [wongdean/rime-settings#7]

**Comment by wongdean** [comment]
待我研究一下，不难的话会加上，请关注后续

**Comment by ClenLu** [comment]
好的  多谢多谢  纯粹用小鹤音形的话  容易提笔忘字 输入多不便  搜狗双拼词库+上小鹤形码作为辅助码的话 那真是太美好了

**Comment by wongdean** [comment]
[小鹤音形方案下载](https://d29vzk4ow07wi7.cloudfront.net/de63dc2ef45d5b094a239fc704051270f3185bf9e883132532b7e17d2fdaf81b?response-content-disposition=attachment%3Bfilename%3D%22weasel-0.14.3.0-installer.exe%22&Policy=eyJTdGF0ZW1lbnQiOiBbeyJSZXNvdXJjZSI6Imh0dHAqOi8vZDI5dnprNG93MDd3aTcuY2xvdWRmcm9udC5uZXQvZGU2M2RjMmVmNDVkNWIwOTRhMjM5ZmM3MDQwNTEyNzBmMzE4NWJmOWU4ODMxMzI1MzJiN2UxN2QyZmRhZjgxYj9yZXNwb25zZS1jb250ZW50LWRpc3Bvc2l0aW9uPWF0dGFjaG1lbnQlM0JmaWxlbmFtZSUzRCUyMndlYXNlbC0wLjE0LjMuMC1pbnN0YWxsZXIuZXhlJTIyIiwiQ29uZGl0aW9uIjp7IkRhdGVMZXNzVGhhbiI6eyJBV1M6RXBvY2hUaW1lIjoxNTg1ODA1MDM0fSwiSXBBZGRyZXNzIjp7IkFXUzpTb3VyY2VJcCI6IjAuMC4wLjAvMCJ9fX1dfQ__&Signature=cEqOUGvpK4SDYnKl83YatYpWchOQCsWJrQRtBMYCp9t6OBa-yJ-C~UIoiWYY8qhrSaWfqHelEVByclKLwonoTRhWtGhB1GmxEaD4acX~qLvUzSbwOSD4c9HR6I2u8KDrWZKv-nQDANPdo4rytlFreNegoWnK3-smi7klFY8ab7Hhik3FTOdAGacs00iowiiRYGc9G2QFqs455iIcxl-CLu~vY9VZb0bP5~nGP7x3jQgMKyCWkuIUKzbyOc3gDLca8D3pcBo63~qFwqR~buWMVg3eIRY~x9p1gt5JutCh4ZkOX9a95fLAyarAFcxAGuIRGku8IkA5O26l5zXyBmY6Dg__&Key-Pair-Id=APKAIFKFWOMXM2UMTSFA)

这是小鹤音形官方提供的鼠须管方案，你要自己替换里面的东西。注意不要替换那几个主要配置文件。
替换完成后，照葫芦画瓢在 `default.custom.yaml` 里加上方案，另外还有用户词典快捷输入你也要改改了。
我不会，所以也没办法测试，只能你自己试试

**Comment by mingcheng** [comment]
> [小鹤音形方案下载](https://d29vzk4ow07wi7.cloudfront.net/de63dc2ef45d5b094a239fc704051270f3185bf9e883132532b7e17d2fdaf81b?response-content-disposition=attachment%3Bfilename%3D%22weasel-0.14.3.0-installer.exe%22&Policy=eyJTdGF0ZW1lbnQiOiBbeyJSZXNvdXJjZSI6Imh0dHAqOi8vZDI5dnprNG93MDd3aTcuY2xvdWRmcm9udC5uZXQvZGU2M2RjMmVmNDVkNWIwOTRhMjM5ZmM3MDQwNTEyNzBmMzE4NWJmOWU4ODMxMzI1MzJiN2UxN2QyZmRhZjgxYj9yZXNwb25zZS1jb250ZW50LWRpc3Bvc2l0aW9uPWF0dGFjaG1lbnQlM0JmaWxlbmFtZSUzRCUyMndlYXNlbC0wLjE0LjMuMC1pbnN0YWxsZXIuZXhlJTIyIiwiQ29uZGl0aW9uIjp7IkRhdGVMZXNzVGhhbiI6eyJBV1M6RXBvY2hUaW1lIjoxNTg1ODA1MDM0fSwiSXBBZGRyZXNzIjp7IkFXUzpTb3VyY2VJcCI6IjAuMC4wLjAvMCJ9fX1dfQ__&Signature=cEqOUGvpK4SDYnKl83YatYpWchOQCsWJrQRtBMYCp9t6OBa-yJ-C~UIoiWYY8qhrSaWfqHelEVByclKLwonoTRhWtGhB1GmxEaD4acX~qLvUzSbwOSD4c9HR6I2u8KDrWZKv-nQDANPdo4rytlFreNegoWnK3-smi7klFY8ab7Hhik3FTOdAGacs00iowiiRYGc9G2QFqs455iIcxl-CLu~vY9VZb0bP5~nGP7x3jQgMKyCWkuIUKzbyOc3gDLca8D3pcBo63~qFwqR~buWMVg3eIRY~x9p1gt5JutCh4ZkOX9a95fLAyarAFcxAGuIRGku8IkA5O26l5zXyBmY6Dg__&Key-Pair-Id=APKAIFKFWOMXM2UMTSFA)
> 
> 这是小鹤音形官方提供的鼠须管方案，你要自己替换里面的东西。注意不要替换那几个主要配置文件。
> 替换完成后，照葫芦画瓢在 `default.custom.yaml` 里加上方案，另外还有用户词典快捷输入你也要改改了。
> 我不会，所以也没办法测试，只能你自己试试

链接打不开 403（可能需要登录的原因？）

**Comment by wongdean** [comment]
https://zhuanlan.zhihu.com/p/113290266

我上面的链接是小鹤官方那个网盘
http://flypy.ys168.com/

你翻翻看
